package ai.sapper.migration.DataMigration.constants;

public enum StructureType {
    CHARACTER, WORD, SEGMENT, VERTICAL_GAP, StructurePair, VGROUP, TABLE, TABLE_CELL,TABLE_ROW, PARA, HIERARCHY,
    PARAGRAPH,BLOCK, LINE, PAGE,
    PDFEMAIL, PDFEMAIL_DATE, PDFEMAIL_FROM,  PDFEMAIL_TO,  PDFEMAIL_CC,  PDFEMAIL_SUB,  PDFEMAIL_ATT,PDFEMAIL_ID,
    PDFEMAIL_GREETING,  PDFEMAIL_SIGN, PDFEMAIL_BODY,PDFEMAIL_IMPORTANCE,
    KEY_VALUE, METADATACELL, SECTION ,TABLE_HEADER,TITLE,REGION,CLICKPOINT, SUBSECTION, TOC, TABLE_HEADER_ATTRIBUTE, LINEGROUP,TABLE_COLUMN;
}
